name: unittest

on:
  push:
    branches:
    - main
    - dev/*
  

jobs:
  test:
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        - name: npm install
          run: |
            npm install

        - name: npm install jest and jsdom
          run: |
            npm install --save-dev jest
            npm install jsdom --save-dev



        - name: npm test
          run: |
            npm test
