name: unittest

on:
  pull_request:
    branches:
      - dev
      - master
  

jobs:
  test:
      runs-on: ubuntu-latest      
      steps:        
        - uses: actions/checkout@v3
        - name: npm install
          run: |
            npm install

        - name: npm install jest and jsdom
          run: |
            npm install --save-dev jest
            npm install jsdom --save-dev

        - name: npm test
          run: |
            npm test
            
  test_changes:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configurar el entorno
        run: |
          npm install
          npm install --save-dev jest
          npm install jsdom --save-dev

      - name: Ejecutar pruebas unitarias en la rama de cambios
        run: |
          npm test

  pr_checks:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
        
      - name: Configurar el entorno
        run: |
          npm install
          npm install --save-dev jest
          npm install jsdom --save-dev

      - name: Ejecutar pruebas unitarias
        run: |
          npm test
